apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: milkbreadbutter-com-tls
spec:
  secretName: milkbreadbutter-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: milkbreadbutter.com
  dnsNames:
    - milkbreadbutter.com
    - www.milkbreadbutter.com